"""empty message

Revision ID: 317e42999772
Revises: 541ec123f462
Create Date: 2024-07-31 14:25:35.580638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317e42999772'
down_revision = '541ec123f462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), server_default='0.0', nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), server_default='0.0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
