"""empty message

Revision ID: 459775ca7813
Revises: 3206401565dc
Create Date: 2024-08-07 20:48:02.083677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459775ca7813'
down_revision = '3206401565dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('place_to_rest_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trip', ['trip_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('place_to_rest_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('trip_id')

    # ### end Alembic commands ###
