"""Update Trip Model

Revision ID: 56de33cdc731
Revises: 2b0de5859ca6
Create Date: 2024-07-23 23:48:17.852783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56de33cdc731'
down_revision = '2b0de5859ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('dates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dates', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.alter_column('budget',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
