"""empty message

Revision ID: 5d05b948ad93
Revises: 97080542da73
Create Date: 2024-08-07 18:02:25.358814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d05b948ad93'
down_revision = '97080542da73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.drop_constraint('place_to_rest_day_id_fkey', type_='foreignkey')
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('place_to_rest_day_id_fkey', 'day', ['day_id'], ['id'])

    # ### end Alembic commands ###
