"""Initial migration

Revision ID: 7f0ea231a94b
Revises: 
Create Date: 2024-07-26 11:06:33.847311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0ea231a94b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude_destination', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude_destination', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.drop_column('startDate')
        batch_op.drop_column('endDate')
        batch_op.drop_column('longitudeDestination')
        batch_op.drop_column('latitudeDestination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitudeDestination', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('longitudeDestination', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('startDate', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('longitude_destination')
        batch_op.drop_column('latitude_destination')

    # ### end Alembic commands ###
