"""Add User and Trip models

Revision ID: 8211fa06d1e4
Revises: 
Create Date: 2024-07-23 00:13:40.862161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8211fa06d1e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('dates', sa.String(), nullable=False),
    sa.Column('bugdet', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('user')
    # ### end Alembic commands ###
