"""empty message

Revision ID: 97080542da73
Revises: e4d8438b7e6b
Create Date: 2024-08-07 17:55:06.340768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97080542da73'
down_revision = 'e4d8438b7e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('place_to_rest_day_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('place_to_rest_day_id_fkey', 'day', ['day_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
