"""Update Trip model to include description and total cost

Revision ID: 9f2086dc3095
Revises: 459775ca7813
Create Date: 2024-08-09 14:52:07.496338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2086dc3095'
down_revision = '459775ca7813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('total_cost')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
