"""empty message

Revision ID: bbee1eec0895
Revises: 8211fa06d1e4
Create Date: 2024-07-23 01:06:28.844851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbee1eec0895'
down_revision = '8211fa06d1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=False))
        batch_op.drop_column('bugdet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bugdet', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
