"""empty message

Revision ID: e1d12770b069
Revises: f5d6fd046765
Create Date: 2024-07-28 02:07:47.165274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d12770b069'
down_revision = 'f5d6fd046765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
