"""empty message

Revision ID: e4d8438b7e6b
Revises: 42f5d17e9a83
Create Date: 2024-08-07 17:27:02.115144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d8438b7e6b'
down_revision = '42f5d17e9a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('itinerary_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('place_to_rest_day_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'itinerary', ['itinerary_id'], ['id'])
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place_to_rest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('place_to_rest_day_id_fkey', 'day', ['day_id'], ['id'])
        batch_op.drop_column('itinerary_id')

    # ### end Alembic commands ###
